text1 = """
The recent development of the highly effective vaccine and antidote to the zombie virus that has been devastating parts of the world for the past 4 years seems to have bought a few problems along with the cure. Governments around the world have been so busy fighting off this terrible plague that nobody has really thought about what would happen to those cured from the disease. And those who have got over the virus are now finding it difficult to reintegrate into society due to the suspicious attitude that almost everybody has developed over the last 4 years of living under the constant fear of zombie attack. 
People have not forgotten that the virus originated from a medicine developed to alleviate the effects of hay fever. The medicine, which sufferers took when their allergy was acting up, has now been banned, of course, but the effects will be felt for years to come; as will the public’s suspicions of pharmaceutical companies.  And as a result, nobody seems completely willing to trust the antidote and vaccine which was developed by the same company that caused the outbreak in the first place. Hay fever sufferers have long since given up taking any medication for their condition. 
There has been a lot of misinformation out there about how the disease can be picked up. Everybody seems to think it can only be passed on to people who have been bitten by zombies. We now know that this is not the case. While a person bitten by a zombie will come down with the disease in less than 48 hours, it is now known that the virus is airborne and can be caught if an infected person coughs or sneezes near somebody who is not. 
The symptoms for the disease also seem to differ according to climate. Infected people in hot countries find that their hands and feet swell up to almost twice their size and then they break out in a purple and green rash all over their bodies. Infected people from colder climates find that it all starts with an inability to keep food down. They start throwing up violently until their stomachs are completely empty and then they pass out. When they come round, they are not yet fully fledged zombies, but the urge to eat human flesh is already starting to affect their judgement. Just like the infected from hotter climates, it takes a few more hours before the sufferers become completely “undead” with an insatiable appetite for brains. 
With the development of the vaccine, there have been some unexpected advantages. Victims of fatal accidents who have contracted the zombie virus, although they have passed away and are declared to be officially dead, can be brought back to life, although wounds to arteries have to be bound up to stop the patients bleeding out and dying once again from blood loss once they have recovered. In fact, there have been several cases of people with fatal diseases being deliberately infected with the virus and then completely pulling through from both their illness and the zombie virus once they have taken the antidote.
However, some people who have had horrible experiences during the peak of the zombie epidemic do not seem to be too keen on having former zombies as their neighbours. Some ex-zombies, although completely recovered, have only been patched up superficially by doctors, and their horrific scars are not the kind of thing you want to see when opening the front door first thing in the morning. And while they may have cut down on their consumption of human flesh to zero, one can only guess what is going on in their once-infected brains. As a consequence, hate crimes against recovered zombies are a problem and it is going to take more than a vaccine to cure the damage done to society as a whole before things can truly return to normal. 
"""

text2 = """
When I set off for work this morning, my car broke down, so I ended up taking the bus. As soon as I got off, I bumped into an old schoolmate, Mark. While we were talking, he brought up something I had already found out from some mutual friends- that he had come into some money and had set up his own business. He told me that there was a lot to sort out, and offered to take me on, but I turned him down straight away.
When I clocked in, my boss had a go at me, telling me off in front of everyone. When I got over the initial shock, I told her I’d make up for being late, but it turned out that she had blown up over a deal that had fallen through, after a client of mine had pulled out of a contract. She told me that I wouldn’t get away with it, that I’d let everybody down, and just went on and on….
Eventually, I ran out of patience and answered back– I said I was not going to put up with it anymore, and if she wanted to lay me off, she should go ahead. Anyway, to cut a long story short, I stormed out, phoned Mark’s secretary, who put me through to him. I told Mark I’d like to take him up on his offer. So, in the end, everything has worked out perfectly!
"""

text3 = """
For his whole life, Nick has never been able to get up early. When he was in elementary school, his mother would set the alarm clock for 6:00 AM, but it would not wake him up. When Nick was in high school, his alarm clock would go off, but he simply turned it off and went back to sleep. Every morning his father would shout, “Come on, Nick! You’re going to be late.” The shouting did not help, however. On a few days, Nick would show up two hours late! Nick knew that his school would not put up with this situation much longer. His parents were frustrated, but they could not give up.
One day Nick’s mom came across a blog on the Internet where people were sharing their stories about oversleeping and different solutions they had come up with to solve their problems. After going over a few of these stories and realizing there could be an underlying health issue, Nick’s mother made up her mind that the best advice was to look for a sleep specialist on the Internet.
After checking out several websites, Nick’s mom found out about a specialist for her son’s condition. She called him up and left a message. The next day, the doctor called her back to talk about Nick’s situation. Now the family is counting on him to help solve Nick’s problem."""

ans1 = ["fighting off", "got over", "acting up", "given up", "picked up", "passed on to", "come down with", "swell up", "break out in", "keep down", "throwing up", "pass out", "come round", "passed away", "bound up", "bleeding out", "pulling through", "patched up", "cut down"]
ans2 = ["set off", "broke down", "ended up", "got off", "bumped into", "brought up", "found out", "set up", "sort out", "take on", "turned down", "clocked in", "had a go at", "telling off", "got over", "make up for", "turned out", "blown up", "fallen through", "pulled out of", "get away with", "let down", "went on", "ran out of", "answered back", "put up with", "lay off", "go ahead", "stormed out", "put through", "take up", "worked out"]
ans3 = ["get up", "wake up", "go off", "turned off", "went back", "come on", "show up", "put up with", "give up", "came across", "come up with", "going over", "made up", "look for", "checking out", "found out", "called up", "called back", "counting on"]
